org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G
org.gradle.daemon=false

systemProp.net.minecraftforge.gradle.repo.recompile.fork=true
systemProp.net.minecraftforge.gradle.repo.recompile.fork.args=-Xmx5G

minecraft_version=1.21.4
minecraft_version_range=[1.21.4,1.21.5)

forge_version=54.1.16
forge_version_range=[54,)
loader_version_range=[54,)

mapping_channel=official
mapping_version=1.21.4

mod_id=ibeeditor
mod_name=IBE Editor
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.github.franckyi.ibeeditor
mod_authors=skadi
mod_description=IBE Editor port for Minecraft 1.21.4